//erro

try{
  //
    throw new Error("deu problema no c√≥digo")
}catch(e){
    console.log(e.name + ": " + e.message);
        

    
}


